version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/source/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Autofac*"
      - dependency-name: "Octopus*"
